command clipboard: user.command_clipboard_toggle()
command clipboard close: user.command_clipboard_disable()
clip <number_small>: user.command_clipboard_repeat_number(number_small)
range clip <number_small> to <number_small>: user.command_clipboard_repeat_range(number_small_1, number_small_2)
multi clip <number_small> (and <number_small>)*: user.command_clipboard_repeat_multi(number_small_list)
macro clip <number_small> (and <number_small>)*: user.command_clipboard_record_macro(number_small_list)
clip macro [play]: user.command_clipboard_play_macro()